# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ISSPassTimes' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ISSPassTimes
	pod 'ReachabilitySwift', '~> 3'

  target 'ISSPassTimesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ISSPassTimesUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
